Silence a false-positive compiler warning in the hostfs code
GCC 9.1 complains:

In file included from /usr/include/string.h:494,
                 from ./uae_cpu/memory-uae.h:37,
                 from ./uae_cpu/cpu_emulation.h:34,
                 from natfeat/hostfs.cpp:28:
In function 'char* strncpy(char*, const char*, size_t)',
    inlined from 'void HostFs::transformFileName(char*, const char*)' at natfeat/hostfs.cpp:994:11:
/usr/include/bits/string_fortified.h:106:34: error: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' output may be truncated copying between 1 and 3 bytes from a string of length 9 [-Werror=stringop-truncation]

While it should be OK to use strncpy in this case, we can also
simply use memcpy here instead, since the string length has been
determined earlier and the trailing NUL is added later.